### ISSUE TITLE
core 模块的 gradle脚本 跑不通！

### ISSUE THREAD

**Issue by xiaofeidev** [guolindev/giffun#12]
java.lang.NoClassDefFoundError: Could not initialize class com.android.build.gradle.internal.crash.PluginCrashReporter

**Comment by xiaofeidev** [comment]
我用的环境是AS 3.2.1

**Comment by MrTaoGe** [comment]
也许你的gradle插件版本有些低了，看看更新一下gradle的版本是否有用。这种问题，一般在控制台应该会有一些提示。

**Comment by xiaofeidev** [comment]
> 也许你的gradle插件版本有些低了，看看更新一下gradle的版本是否有用。这种问题，一般在控制台应该会有一些提示。

感谢解答，我下班再去研究一下

**Comment by hbh520** [comment]
我gradle版本4.10.1正常

**Comment by xiaofeidev** [comment]
> 我gradle版本4.10.1正常

确实估计是我公司电脑开发环境的事，我自己电脑上运行一切正常！尬尴！
