### ISSUE TITLE
后期是否会考虑发布 Java 版本的项目呢？

### ISSUE THREAD

**Issue by gs666** [guolindev/giffun#16]
还没有掌握 Kotlin~

**Comment by rcj60560** [comment]
+1 期待java版本！

**Comment by rcj60560** [comment]
@guolindev

**Comment by MrTaoGe** [comment]
我感觉这正是各位的机会，各位可以根据这个版本的代码，自己撸一份java版本，甚至flutter，weex，react-native，小程序等版本的项目，就当是练手了，当然，可能用到的资源以及许可之类的可以先找郭婶确认一下，我只是提个意见，哈哈。

**Comment by yongdaimi** [comment]
下载来看下，竟然是kotlin版本的，郭神NB

**Comment by gs666** [comment]
> 我感觉这正是各位的机会，各位可以根据这个版本的代码，自己撸一份java版本，甚至flutter，weex，react-native，小程序等版本的项目，就当是练手了，当然，可能用到的资源以及许可之类的可以先找郭婶确认一下，我只是提个意见，哈哈。

主要是我目前还是个Android新人，还有很多要学习的开发知识，Kotlin学习还要往后稍稍=-=

**Comment by gs666** [comment]
> 下载来看下，竟然是kotlin版本的，郭神NB

可能是因为郭婶计划书写《第一行代码》第三版，全部使用Kotlin

**Comment by shenbuqingyun** [comment]
flutter，第三版应该包含了，甚至可能是主体内容。

**Comment by mackwu828** [comment]
赶紧学 kotlin 吧，界面还用 java 写，可读性是真的差

**Comment by gs666** [comment]
> 赶紧学 kotlin 吧，界面还用 java 写，可读性是真的差

此言差矣，公司这么多项目很难转啊

**Comment by guolindev** [comment]
不好意思，不会有java版的了，同一份代码再使用java语言写一遍，那可真要把我折腾死了。
