### ISSUE TITLE
项目能成功运行 但是会报红，主要是是R找不到的警报，需要怎么弄一下呢，感谢大神们的帮忙～

### ISSUE THREAD

**Issue by yangzai100** [guolindev/giffun#20]

**Comment by MrTaoGe** [comment]
R文件找不到的原因很多，最好是描述的具体点，把出错的日志看一下，贴个图出来。之前频繁遇到的一个导致R文件找不到的问题是gradle升级以后，项目目录下build.gradle里依赖kotlin-jdk的写法失效，之前是
org.jetbrains.kotlin:kotlin-stdlib-**jre7**,现在应该是org.jetbrains.kotlin:kotlin-stdlib-**jdk7**，不知道你是不是这个问题。(注意加粗地方的区别)

**Comment by hbh520** [comment]
这不会影响正常运行的，应该是kotlin引起的

**Comment by linxingxi** [comment]
我的也遇到了，但不影响编译运行。但是具体是什么引起的不清楚，再研究下

**Comment by LRaccoon** [comment]
kotlin编辑器的插件版本和Gradle配置的版本不一致吧。
该Gradle或者升级下编辑器的Kotlin插件

**Comment by Taonce** [comment]
@MrTaoGe 郭老师用的是Gradle3.3版本，你那边可以把3.3换成3.1.3，properties文件也换下，换成适合自己的版本就行了，我刚弄好，如果还不行可以艾特我。

**Comment by yangzai100** [comment]
@MrTaoGe 我这边换成3.13 R文件也不报错了，知道为什么吗？

**Comment by yangzai100** [comment]
@Taonce 我这边换成3.13就可以了，知道为什么吗？

**Comment by MrTaoGe** [comment]
@yangzai100 我先说句可能是废话的话，哈。一般出这种错，在android studio的控制台窗口有提示，这应该能让你看到是哪里出错以及为什么。然后我再说一下我理解的这个问题：gradle是一个构建工具，并不是只用在android中(这个大家应该都知道),它针对不同语言有不同的插件，gradle-android就是其中之一。更多的你有兴趣可以看下这篇文章的末尾总结：https://blog.csdn.net/Builder_Taoge/article/details/70228791
，里面说的对或错只是一己之见，没有经过求证。但我猜想，如果你改成3.13就OK了，那么可能在你的项目目录/gradle/wrapper/gradle-wrapper.properties文件中的gradle版本要低于4.10.1-all,不知道是不是这样。

**Comment by yangzai100** [comment]
@Taonce 目录/gradle/wrapper/gradle-wrapper.properties文件中的gradle版本有三个一个4.1，一个4.4，一个4.6，确实对grandle不是很熟悉，要好好学习～
