### ISSUE TITLE
关于手机号登陆界面的优化点

### ISSUE THREAD

**Issue by Taonce** [guolindev/giffun#22]
输入手机号，点击发送验证码按钮之后，发现手机号输入错误，这时候修改了手机号，但是按钮还在倒计时，不可点击，这一点可否稍作修改呢？

**Comment by guolindev** [comment]
肯定不行呀，你也可以参考一下别的app短信验证码这块是怎么做的，强制60秒倒计时是一种短信防刷机制，如果改一个手机号就重置时间，那太容易刷短信了，没有app会用这种方式的，因为每条短信都是钱。

**Comment by Taonce** [comment]
@guolindev 谢谢郭老师，长见识了
