### ISSUE TITLE
建议更改开源协议

### ISSUE THREAD

**Issue by h2562961224** [guolindev/giffun#25]
“当然，如果你是通过这个App的源码学到了很多知识，然后应用到了自己的项目当中，这种我是非常欢迎的，但如果只是在我的源码基础上稍微改了改代码或者界面，然后就拿去用作赚钱目的，这种行为是不被允许的。”

Apache License 2.0，商用完全是可以的。。。。防止在非授权的情况下商用，建议使用GPL，LGPL，AGPL等协议

**Comment by oneisall8955** [comment]
GPL/LGPL +1

**Comment by winter-dev** [comment]
意思是在 Apache License 2.0 协议下  我在“源码基础上稍微改了改代码或者界面，然后就拿去用作赚钱“  。是可以是的是吧。

**Comment by guolindev** [comment]
遗憾的是，我没有在github的支持协议里面找到GPL/LGPL，在头部加入说明提醒一下就好了，这款开源app目的在于方便学习。
