### ISSUE TITLE
使用用户名验证码登陆后，进入主页，返回后竟然会退到登陆页面

### ISSUE THREAD

**Issue by xumingyi** [guolindev/giffun#28]
郭神，登陆后返回应该直接退出程序，不应该回到手机号验证码登陆页面了

**Comment by mackwu828** [comment]
应用宝上下的1.0.3正式版，按返回键退不出去，按home键每次进入都要从启动页进入

**Comment by Kestcon** [comment]
> 应用宝上下的1.0.3正式版，按返回键退不出去，按home键每次进入都要从启动页进入

这个问题杀掉应用后再启动应该就没问题了

**Comment by xumingyi** [comment]
> > 应用宝上下的1.0.3正式版，按返回键退不出去，按home键每次进入都要从启动页进入
> 
> 这个问题杀掉应用后再启动应该就没问题了

杀掉再次进没问题， 因为再次进入不会再进手机号登陆页面了不是嘛

**Comment by Kestcon** [comment]
> > > 应用宝上下的1.0.3正式版，按返回键退不出去，按home键每次进入都要从启动页进入
> > 
> > 
> > 这个问题杀掉应用后再启动应该就没问题了
> 
> 杀掉再次进没问题， 因为再次进入不会再进手机号登陆页面了不是嘛

杀应用再启动是回复上面那位兄弟提出的每次按home键后再进入都要从启动页进入的问题

**Comment by guolindev** [comment]
此问题已修复，感谢指出。
