### ISSUE TITLE
好多废弃的api，导致无法编译，目前代码总是无法生成R文件

### ISSUE THREAD

**Issue by tianshaokai** [guolindev/giffun#31]
![image](https://user-images.githubusercontent.com/6706496/51984778-1aefc300-24d7-11e9-9fd0-eca43d79693c.png)

**Comment by tianshaokai** [comment]
低版本升级安装新版导致主页面启动两次

**Comment by kscMaster** [comment]
没出现你说的情况，我的IDE都是最新版的

**Comment by tianshaokai** [comment]
我升级到最新as ，目前没有发现该问题
