### ISSUE TITLE
R文件一直生成不了，但是项目能运行。

### ISSUE THREAD

**Issue by chuwe1** [guolindev/giffun#34]
git glone下来了。
编译之后没有R文件，没法点 ctrl + 左键 去看布局 还有一堆的标红是真的难受啊。
奇怪的是，项目居然能运行，app能跑起来，也不报错。这我想要找那个资源文件出错了去改都没地儿找。是真的难受啊。

**Comment by taoszu** [comment]
可能是R文件过大了，可以配置一下R文件的大小。

**Comment by hefuweill** [comment]
手动把R文件大小从2500，改大成5000，还是不行。

**Comment by chuwe1** [comment]
> 可能是R文件过大了，可以配置一下R文件的大小。

同 @hefuweill 已经改成5000 依然这样

**Comment by Qiang11** [comment]
我的也是

**Comment by xiaomaothm** [comment]
一样的问题

**Comment by Taonce** [comment]
@chuwe1 请看问题 #20

**Comment by guolindev** [comment]
看一下这里 https://github.com/guolindev/giffun/issues/20
