### ISSUE TITLE
R文件报红，但是项目能运行

### ISSUE THREAD

**Issue by dacaoyuan** [guolindev/giffun#39]
项目中所有的R文件都报红，但是项目能运行。有说是因为app过大，超过了R文件的默认大小。这样配置了idea.max.intellisense.filesize=5000 也是不行的。请问，这个怎么办呢？

**Comment by zhangwenhaojf40** [comment]
> 项目中所有的R文件都报红，但是项目能运行。有说是因为app过大，超过了R文件的默认大小。这样配置了idea.max.intellisense.filesize=5000 也是不行的。请问，这个怎么办呢？

classpath 'com.android.tools.build:gradle:3.3.0'改成classpath 'com.android.tools.build:gradle:3.2.1'
对应的gradle-wrapper.properties文件中改成distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
试一下

**Comment by Taonce** [comment]
@dacaoyuan 可以跳转到 #20

**Comment by anroidjuanbudongle** [comment]
@dacaoyuan 你可以设置Gradle Version 4.6  Android plugin Version 3.2.1,我目前这么配置的,R文件已正常

**Comment by dacaoyuan** [comment]
是的解决了，多谢回答！ @zhangwenhaojf40 @Taonce
