### ISSUE TITLE
ParallaxImageView 设置了scaleType="fitXY" 为什么gif在宽度小于高度的时候，宽度没有铺满屏幕

### ISSUE THREAD

**Issue by goingSonny** [guolindev/giffun#56]
在FeedDetailActivity 的布局里面使用了ParallaxImageView ， 设置了scaleType="fitXY" 但是在gif图片的宽度小于高度的时候，gif的 宽度并没有铺满屏幕的宽度，大佬能解释一下嘛，我看ParallaxImageView 里面只做了偏移量的处理，谢谢！

**Comment by guolindev** [comment]
因为giffun的播放gif技术使用的都是glide框架里面提供的内容，而glide并不支持fixXY这种拉伸模式，具体原因你可以参考一下我之前写的文章glide图片变换这篇文章 https://blog.csdn.net/guolin_blog/article/details/71524668
